services:
  redis:
    image: redis:7-alpine
    container_name: devtrace-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  opensearch:
    image: opensearchproject/opensearch:2.16.0
    container_name: devtrace-opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=DevTrace@123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9600:9600"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: devtrace-backend
    env_file:
      - ./backend/.env
    environment:
      REDIS_URL: redis://redis:6379
      OPENSEARCH_NODE: http://opensearch:9200
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - opensearch
    restart: unless-stopped

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: devtrace-worker
    env_file:
      - ./backend/.env
    environment:
      REDIS_URL: redis://redis:6379
      OPENSEARCH_NODE: http://opensearch:9200
    depends_on:
      - redis
      - opensearch
      - backend
    restart: unless-stopped

volumes:
  redis-data:
  opensearch-data: